import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/component/Navbar";
import Footer from "@/component/Footer";
import localFont from 'next/font/local'


const familyFont = localFont({
  src: [
    {
      path: '../public/font/Yekan-Bakh-Family/ttf/YekanBakh-Regular.ttf',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../public/font/yekan-bakh-fanum/ttf/YekanBakhFaNum-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/font/Yekan-Bakh-NoEn/ttf/YekanBakhNoEn-Regular.ttf',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-family',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" className={familyFont.variable}>
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
